# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo sudo snap install --classic heroku
  displayName: 'Install Heroku CLI'

- script: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  displayName: 'Login to Heroku container register with Docker'
  env:
    HEROKU_API_KEY: $(Heroku API Key)

- script: heroku container:push web -a realisesoftware
  displayName: 'Push container to Heroku'
  workingDirectory: 'realise.software'
  env:
    HEROKU_API_KEY: $(Heroku API Key)

- script: heroku container:release web -a realisesoftware
  displayName: 'Release container to Heroku'
  workingDirectory: 'realise.software'
  env:
    HEROKU_API_KEY: $(Heroku API Key)